[browser]
gatherUsageStats = false
serverAddress = "localhost"

[server]
enableCORS = false
enableXsrfProtection = false

[server.headless]
enableCORS = false

[server.customHeaders]
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdn.plot.ly; style-src 'self' 'unsafe-inline'"